name: Docker Build and Push

on:
  push:
    branches:
      - master  # เปลี่ยนเป็น master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ขั้นตอนแรก: Checkout โค้ดจาก repository
    - name: Checkout code
      uses: actions/checkout@v2

    # ขั้นตอนที่สอง: ใช้ docker/login-action@v2 เพื่อ login เข้าสู่ Docker Hub โดยใช้ secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # ขั้นตอนที่สาม: Build Docker image
    - name: Build Docker image
      run: docker build -t imsuriyapi/react-docker-test:0.2 .

    # ขั้นตอนที่สี่: Push Docker image ไปที่ Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push imsuriyapi/react-docker-test:0.2
